[package]
name = "blast_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
blast_core = { path = "../blast_core" }
tokio = { version = "1.37.0", features = ["full"] }
simplelog = "0.12.2"
log = "0.4.20"
ratatui = "0.27.0"
