name: Main Workflow
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install -y jq bc autoconf automake build-essential git libtool libsqlite3-dev python3 python3-pip net-tools zlib1g-dev libsodium-dev gettext
      - name: Install Python Dependencies
        run: |
          sudo apt-get install python3.12-venv
          python3 -m venv ~/.venv
          ~/.venv/bin/pip3 install mako
          ~/.venv/bin/pip3 install grpcio-tools
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Installing protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.33.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Checkout BLAST
        uses: actions/checkout@v4
      - name: Build All
        run: ./build.sh
