name: Main Workflow
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Checkout BLAST
        uses: actions/checkout@v4
      - name: Build All
        run: ./build.sh
