name: Main Workflow
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.13'
      - name: Install python dependencies
        run: |
          pip3 --version
          pip --version
          pip3 install --upgrade pip
          pip3 install mako
          pip3 install grpcio-tools
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Installing protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.33.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
          echo "$HOME/go/bin" >> $GITHUB_PATH
      - name: Checkout BLAST
        uses: actions/checkout@v4
      - name: Build All
        run: ./build.sh
